set(HUMOTO_BUILD_REGRESSION_TESTS       OFF     CACHE BOOL "")
set(HUMOTO_BUILD_TESTS                  OFF     CACHE BOOL "")
set(HUMOTO_DEBUG                        ON      CACHE BOOL "")
set(HUMOTO_ENABLE_THREADS_FOR_LOGGING   ON      CACHE BOOL "")

set(HUMOTO_ENABLE_MODULES_BY_DEFAULT    OFF     CACHE BOOL "")

set(HUMOTO_ENABLE_BRIDGES_BY_DEFAULT    OFF     CACHE BOOL "")
set(HUMOTO_INSTALL_BRIDGES              ON      CACHE BOOL "")
set(HUMOTO_BRIDGE_config_yaml           ON      CACHE BOOL "")
set(HUMOTO_BRIDGE_qpOASES               ON      CACHE BOOL "")
